//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONIX.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Good
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Good()
        {
            this.ExpenceInvoiceSpecification = new HashSet<ExpenceInvoiceSpecification>();
            this.GoodNDS = new HashSet<GoodNDS>();
            this.GoodPrice = new HashSet<GoodPrice>();
            this.Parameter = new HashSet<Parameter>();
            this.SaleContractSpecification = new HashSet<SaleContractSpecification>();
        }
    
        public int Id { get; set; }
        public int IdManufacturer { get; set; }
        public Nullable<int> IdCategory { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] Sertificate { get; set; }
        public byte[] TechnicalDataSheet { get; set; }
        public byte[] Instruction { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] PreviewImage { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenceInvoiceSpecification> ExpenceInvoiceSpecification { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodNDS> GoodNDS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodPrice> GoodPrice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parameter> Parameter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleContractSpecification> SaleContractSpecification { get; set; }
    }
}
